name: gym-duckietown
channels:
    - pytorch
    - defaults
dependencies:
    - python
    - pytorch
    - torchvision
    - tensorflow
    - pyzmq
    - numpy
    - pyyaml
    - termcolor
    - opencv
    - pip
    - pip:
        - gym
        - pyglet
        - opencv-python
        - scikit-image
